// RFC_4122.UUID.Generation.swift
// UUID generation for RFC 4122 versions (v3, v4, v5)

// MARK: - Namespace UUIDs (RFC 4122 Appendix C)

extension RFC_4122.UUID {
    /// Namespace UUID for DNS names (RFC 4122 Appendix C).
    ///
    /// UUID: `6ba7b810-9dad-11d1-80b4-00c04fd430c8`
    public static let dns = Self(
        bytes: (
            0x6b, 0xa7, 0xb8, 0x10,
            0x9d, 0xad, 0x11, 0xd1,
            0x80, 0xb4, 0x00, 0xc0,
            0x4f, 0xd4, 0x30, 0xc8
        )
    )

    /// Namespace UUID for URLs (RFC 4122 Appendix C).
    ///
    /// UUID: `6ba7b811-9dad-11d1-80b4-00c04fd430c8`
    public static let url = Self(
        bytes: (
            0x6b, 0xa7, 0xb8, 0x11,
            0x9d, 0xad, 0x11, 0xd1,
            0x80, 0xb4, 0x00, 0xc0,
            0x4f, 0xd4, 0x30, 0xc8
        )
    )

    /// Namespace UUID for ISO OIDs (RFC 4122 Appendix C).
    ///
    /// UUID: `6ba7b812-9dad-11d1-80b4-00c04fd430c8`
    public static let oid = Self(
        bytes: (
            0x6b, 0xa7, 0xb8, 0x12,
            0x9d, 0xad, 0x11, 0xd1,
            0x80, 0xb4, 0x00, 0xc0,
            0x4f, 0xd4, 0x30, 0xc8
        )
    )

    /// Namespace UUID for X.500 DNs (RFC 4122 Appendix C).
    ///
    /// UUID: `6ba7b814-9dad-11d1-80b4-00c04fd430c8`
    public static let x500 = Self(
        bytes: (
            0x6b, 0xa7, 0xb8, 0x14,
            0x9d, 0xad, 0x11, 0xd1,
            0x80, 0xb4, 0x00, 0xc0,
            0x4f, 0xd4, 0x30, 0xc8
        )
    )
}

// MARK: - Version 3 Generation (MD5)

extension RFC_4122.UUID {
    /// Generates a version 3 UUID from a namespace UUID and name using MD5 hashing.
    ///
    /// Version 3 UUIDs are generated by hashing a namespace UUID concatenated with
    /// a name using MD5. The same namespace and name always produce the same UUID.
    ///
    /// - Parameters:
    ///   - namespace: The namespace UUID (e.g., `Namespace.dns`).
    ///   - name: The name to hash (as UTF-8 bytes).
    ///   - hashProvider: A hash provider that implements MD5.
    /// - Returns: A version 3 UUID.
    ///
    /// ## Example
    ///
    /// ```swift
    /// let uuid = RFC_4122.UUID.v3(
    ///     namespace: .dns,
    ///     name: "www.example.com",
    ///     using: MyHashProvider()
    /// )
    /// // Always produces: 5df41881-3aed-3515-88a7-2f4a814cf09e
    /// ```
    public static func v3<H: RFC_4122.HashProvider>(
        namespace: Self,
        name: String,
        using hashProvider: H
    ) -> Self {
        v3(namespace: namespace, nameBytes: Array(name.utf8), using: hashProvider)
    }

    /// Generates a version 3 UUID from a namespace UUID and name bytes using MD5 hashing.
    ///
    /// - Parameters:
    ///   - namespace: The namespace UUID.
    ///   - nameBytes: The name as raw bytes.
    ///   - hashProvider: A hash provider that implements MD5.
    /// - Returns: A version 3 UUID.
    public static func v3<H: RFC_4122.HashProvider>(
        namespace: Self,
        nameBytes: [UInt8],
        using hashProvider: H
    ) -> Self {
        // Concatenate namespace UUID bytes with name bytes
        var data = namespace.byteArray
        data.append(contentsOf: nameBytes)

        // Compute MD5 hash (16 bytes)
        let hash = hashProvider.md5(data)
        precondition(hash.count == 16, "MD5 hash must be 16 bytes")

        var bytes = (
            hash[0], hash[1], hash[2], hash[3],
            hash[4], hash[5], hash[6], hash[7],
            hash[8], hash[9], hash[10], hash[11],
            hash[12], hash[13], hash[14], hash[15]
        )

        // Set version 3 in byte 6, high nibble
        bytes.6 = (bytes.6 & 0x0F) | 0x30

        // Set RFC 4122 variant in byte 8, high 2 bits
        bytes.8 = (bytes.8 & 0x3F) | 0x80

        return Self(bytes: bytes)
    }
}

// MARK: - Version 5 Generation (SHA-1)

extension RFC_4122.UUID {
    /// Generates a version 5 UUID from a namespace UUID and name using SHA-1 hashing.
    ///
    /// Version 5 UUIDs are generated by hashing a namespace UUID concatenated with
    /// a name using SHA-1. The same namespace and name always produce the same UUID.
    /// Version 5 is preferred over version 3 as SHA-1 is more collision-resistant than MD5.
    ///
    /// - Parameters:
    ///   - namespace: The namespace UUID (e.g., `Namespace.dns`).
    ///   - name: The name to hash (as UTF-8 bytes).
    ///   - hashProvider: A hash provider that implements SHA-1.
    /// - Returns: A version 5 UUID.
    ///
    /// ## Example
    ///
    /// ```swift
    /// let uuid = RFC_4122.UUID.v5(
    ///     namespace: .dns,
    ///     name: "www.example.com",
    ///     using: MyHashProvider()
    /// )
    /// // Always produces: 2ed6657d-e927-568b-95e1-2665a8aea6a2
    /// ```
    public static func v5<H: RFC_4122.HashProvider>(
        namespace: Self,
        name: String,
        using hashProvider: H
    ) -> Self {
        v5(namespace: namespace, nameBytes: Array(name.utf8), using: hashProvider)
    }

    /// Generates a version 5 UUID from a namespace UUID and name bytes using SHA-1 hashing.
    ///
    /// - Parameters:
    ///   - namespace: The namespace UUID.
    ///   - nameBytes: The name as raw bytes.
    ///   - hashProvider: A hash provider that implements SHA-1.
    /// - Returns: A version 5 UUID.
    public static func v5<H: RFC_4122.HashProvider>(
        namespace: Self,
        nameBytes: [UInt8],
        using hashProvider: H
    ) -> Self {
        // Concatenate namespace UUID bytes with name bytes
        var data = namespace.byteArray
        data.append(contentsOf: nameBytes)

        // Compute SHA-1 hash (20 bytes, we only use first 16)
        let hash = hashProvider.sha1(data)
        precondition(hash.count == 20, "SHA-1 hash must be 20 bytes")

        // Use only first 16 bytes of the hash
        var bytes = (
            hash[0], hash[1], hash[2], hash[3],
            hash[4], hash[5], hash[6], hash[7],
            hash[8], hash[9], hash[10], hash[11],
            hash[12], hash[13], hash[14], hash[15]
        )

        // Set version 5 in byte 6, high nibble
        bytes.6 = (bytes.6 & 0x0F) | 0x50

        // Set RFC 4122 variant in byte 8, high 2 bits
        bytes.8 = (bytes.8 & 0x3F) | 0x80

        return Self(bytes: bytes)
    }
}

// MARK: - Version 4 Generation (Random)

extension RFC_4122.UUID {
    /// Generates a version 4 (random) UUID.
    ///
    /// Version 4 UUIDs contain 122 bits of random data with version (4)
    /// and variant (RFC 4122) bits set appropriately.
    ///
    /// - Parameter random: A random provider for generating random bytes.
    /// - Returns: A version 4 UUID.
    /// - Throws: `RandomError` if random bytes cannot be generated.
    ///
    /// ## Example
    ///
    /// ```swift
    /// let uuid = try RFC_4122.UUID.v4(using: SystemRandom())
    /// print(uuid.version)  // Optional(.v4)
    /// ```
    public static func v4<R: RFC_4122.RandomProvider>(
        using random: R
    ) throws(R.RandomError) -> Self {
        var bytes:
            (
                UInt8, UInt8, UInt8, UInt8,
                UInt8, UInt8, UInt8, UInt8,
                UInt8, UInt8, UInt8, UInt8,
                UInt8, UInt8, UInt8, UInt8
            ) = (0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)

        let outcome: Result<Void, R.RandomError> = Swift.withUnsafeMutableBytes(of: &bytes) { buffer in
            do throws(R.RandomError) {
                try random.fill(buffer)
                return .success(())
            } catch {
                return .failure(error)
            }
        }
        try outcome.get()

        // Set version 4 in byte 6, high nibble
        bytes.6 = (bytes.6 & 0x0F) | 0x40

        // Set RFC 4122 variant in byte 8, high 2 bits
        bytes.8 = (bytes.8 & 0x3F) | 0x80

        return Self(bytes: bytes)
    }

    /// Generates a version 4 (random) UUID using a closure for random bytes.
    ///
    /// - Parameter fillRandom: A closure that fills the provided buffer with random bytes.
    /// - Returns: A version 4 UUID.
    /// - Throws: Any error thrown by the `fillRandom` closure.
    public static func v4<E: Swift.Error>(
        fillRandom: (UnsafeMutableRawBufferPointer) throws(E) -> Void
    ) throws(E) -> Self {
        var bytes:
            (
                UInt8, UInt8, UInt8, UInt8,
                UInt8, UInt8, UInt8, UInt8,
                UInt8, UInt8, UInt8, UInt8,
                UInt8, UInt8, UInt8, UInt8
            ) = (0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)

        let outcome: Result<Void, E> = Swift.withUnsafeMutableBytes(of: &bytes) { buffer in
            do throws(E) {
                try fillRandom(buffer)
                return .success(())
            } catch {
                return .failure(error)
            }
        }
        try outcome.get()

        // Set version 4
        bytes.6 = (bytes.6 & 0x0F) | 0x40

        // Set RFC 4122 variant
        bytes.8 = (bytes.8 & 0x3F) | 0x80

        return Self(bytes: bytes)
    }
}
